In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import re
import xgboost

from pandas.api.types import CategoricalDtype

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_log_error
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from statsmodels.graphics.tsaplots import plot_pacf
from xgboost import XGBRegressor
import lightgbm

In [2]:
all_csv = pd.read_csv('cleaned.csv.gz',
                 dtype = {
                     'store_nbr' : 'category',
                     'family' : 'category',
                     'sales': 'float',
                     'city': 'category',
                     'state': 'category',
                     'type': 'category',
                     'holiday_type': 'category',
                     'holiday_transferred': 'category'
                 },
                  parse_dates=['date'])
all_csv['date'] = pd.to_datetime(all_csv['date']).dt.to_period('D')

In [3]:
all = all_csv.copy()  # we can start experimenting from here without reloading the csv file

In [4]:
# this is for experimentation

filter_by_stores = None  # note: please use string here (unlike Mine.ipynb)
filter_by_family = None
filter_by_dates = None

#filter_by_stores = ['15']  # note: please use string here (unlike Mine.ipynb)
#filter_by_family = ['PRODUCE', 'AUTOMOBILE']
#filter_by_dates = '2014-06-05'

In [5]:
if filter_by_dates == None:
    train_start_date = '2013-01-01'
else:
    train_start_date = filter_by_dates
train_end_date = '2017-08-15'
test_start_date = '2017-08-16'
test_end_date = '2017-08-31'

In [6]:
if filter_by_family != None:
    all = all[all['family'].isin(filter_by_family)]
if filter_by_stores != None:
    all = all[all['store_nbr'].isin(filter_by_stores)]
if filter_by_dates != None:
    all = all[all['date'] >= filter_by_dates]

In [7]:
all['store_nbr'].unique()

['1', '10', '11', '12', '13', ..., '54', '6', '7', '8', '9']
Length: 54
Categories (54, object): ['1', '10', '11', '12', ..., '6', '7', '8', '9']

In [8]:
all.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3036528 entries, 0 to 3036527
Data columns (total 38 columns):
 #   Column               Dtype    
---  ------               -----    
 0   date                 period[D]
 1   store_nbr            category 
 2   family               category 
 3   sales                float64  
 4   onpromotion          int64    
 5   sales_lag_01         float64  
 6   sales_lag_02         float64  
 7   sales_lag_03         float64  
 8   sales_lag_04         float64  
 9   sales_lag_05         float64  
 10  sales_lag_06         float64  
 11  sales_lag_07         float64  
 12  sales_lag_08         float64  
 13  sales_lag_09         float64  
 14  sales_lag_10         float64  
 15  sales_lag_11         float64  
 16  sales_lag_12         float64  
 17  sales_lag_13         float64  
 18  sales_lag_14         float64  
 19  sales_lag_15         float64  
 20  sales_lag_16         float64  
 21  sales_lag_17         float64  
 22  sales_lag_18      

## One Hot Encoding

In [9]:
def one_hot_encode(df):
    ohe = OneHotEncoder()
    #ohe.fit_transform(df[column])
    return pd.get_dummies(data=df, columns=['store_nbr', 'family', 'city', 'state', 'type',
                                     'cluster', 'holiday_type', 'holiday_transferred', 'weekday'])    

In [10]:
all_ohe = one_hot_encode(all)
all_ohe = all_ohe.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))  # remove bad char in column names

X = all_ohe[all_ohe['date'] <= train_end_date]
X = X.drop(['sales'], axis=1)
y = all_ohe[['date', 'sales']][all_ohe['date'] <= train_end_date]
y.set_index('date', inplace=True)

X_test = all_ohe[all_ohe['date'] >= test_start_date]
X_test = X_test.drop(['sales'], axis=1)

X.drop('date', axis=1, inplace=True)
X_test.drop('date', axis=1, inplace=True)
y.set_index(X.index, inplace=True)

X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=1)

## Experiment I -- Linear Regression

In [11]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred_train = lr.predict(X_train)
y_pred_train[y_pred_train < 0] = 0
y_pred_val = lr.predict(X_val)
y_pred_val[y_pred_val < 0] = 0

print("RMS log-error train: ", np.sqrt(mean_squared_log_error(y_train, y_pred_train)))
print("RMS log-error val: ", np.sqrt(mean_squared_log_error(y_val, y_pred_val)))

RMS log-error train:  0.16114945261294478
RMS log-error val:  0.16183534811749348


## Experiment II -- Lightgbm

In [13]:
lgb_params = {
    'boosting_type' : 'gbdt',  # gradient boosting decision tree
    'early_stopping_rounds': 200,
    'force_col_wise': True,
    'learning_rate': 0.1,
    'max_depth': 10,
    'metric': 'mse',  # mean square error
    'num_iterations': 5000,
    'num_leaves': 10,
    'random_state': 1,
    'verbose': 0
}

X_train_lgb = lightgbm.Dataset(data=X_train, label=y_train, feature_name='auto')
X_val_lgb = lightgbm.Dataset(data=X_val, label=y_val, reference=X_train_lgb, feature_name='auto')

In [14]:
lgb = lightgbm.train(
    params=lgb_params, 
    train_set=X_train_lgb,
    valid_sets=[X_train_lgb, X_val_lgb],
)

/usr/local/lib/python3.9/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


[1]	training's l2: 4.90168	valid_1's l2: 4.91242
Training until validation scores don't improve for 200 rounds
[2]	training's l2: 4.02867	valid_1's l2: 4.0381
[3]	training's l2: 3.31896	valid_1's l2: 3.32735
[4]	training's l2: 2.74165	valid_1's l2: 2.74905
[5]	training's l2: 2.26981	valid_1's l2: 2.27645
[6]	training's l2: 1.88693	valid_1's l2: 1.89284
[7]	training's l2: 1.57317	valid_1's l2: 1.57847
[8]	training's l2: 1.31788	valid_1's l2: 1.32251
[9]	training's l2: 1.1096	valid_1's l2: 1.11375
[10]	training's l2: 0.93936	valid_1's l2: 0.943075
[11]	training's l2: 0.800775	valid_1's l2: 0.804217
[12]	training's l2: 0.688043	valid_1's l2: 0.691191
[13]	training's l2: 0.595532	valid_1's l2: 0.598386
[14]	training's l2: 0.520251	valid_1's l2: 0.522885
[15]	training's l2: 0.458727	valid_1's l2: 0.461112
[16]	training's l2: 0.40845	valid_1's l2: 0.410705
[17]	training's l2: 0.367455	valid_1's l2: 0.369544
[18]	training's l2: 0.333578	valid_1's l2: 0.335556
[19]	training's l2: 0.30593	valid

[158]	training's l2: 0.157119	valid_1's l2: 0.158281
[159]	training's l2: 0.157056	valid_1's l2: 0.158229
[160]	training's l2: 0.156985	valid_1's l2: 0.158155
[161]	training's l2: 0.156918	valid_1's l2: 0.15809
[162]	training's l2: 0.156849	valid_1's l2: 0.158023
[163]	training's l2: 0.156836	valid_1's l2: 0.158007
[164]	training's l2: 0.156763	valid_1's l2: 0.157934
[165]	training's l2: 0.156668	valid_1's l2: 0.15783
[166]	training's l2: 0.156613	valid_1's l2: 0.157785
[167]	training's l2: 0.156584	valid_1's l2: 0.157772
[168]	training's l2: 0.156533	valid_1's l2: 0.157742
[169]	training's l2: 0.156488	valid_1's l2: 0.157696
[170]	training's l2: 0.156409	valid_1's l2: 0.15762
[171]	training's l2: 0.156357	valid_1's l2: 0.157571
[172]	training's l2: 0.1562	valid_1's l2: 0.157418
[173]	training's l2: 0.156168	valid_1's l2: 0.157388
[174]	training's l2: 0.156128	valid_1's l2: 0.157357
[175]	training's l2: 0.156093	valid_1's l2: 0.157321
[176]	training's l2: 0.156035	valid_1's l2: 0.15726

[315]	training's l2: 0.149728	valid_1's l2: 0.151473
[316]	training's l2: 0.14972	valid_1's l2: 0.151466
[317]	training's l2: 0.149627	valid_1's l2: 0.151332
[318]	training's l2: 0.149594	valid_1's l2: 0.151307
[319]	training's l2: 0.149557	valid_1's l2: 0.151266
[320]	training's l2: 0.149536	valid_1's l2: 0.151253
[321]	training's l2: 0.149507	valid_1's l2: 0.151227
[322]	training's l2: 0.149473	valid_1's l2: 0.151198
[323]	training's l2: 0.14946	valid_1's l2: 0.15119
[324]	training's l2: 0.149437	valid_1's l2: 0.151172
[325]	training's l2: 0.149426	valid_1's l2: 0.151161
[326]	training's l2: 0.149417	valid_1's l2: 0.151153
[327]	training's l2: 0.149406	valid_1's l2: 0.151142
[328]	training's l2: 0.149394	valid_1's l2: 0.151131
[329]	training's l2: 0.149383	valid_1's l2: 0.151122
[330]	training's l2: 0.149372	valid_1's l2: 0.151113
[331]	training's l2: 0.149328	valid_1's l2: 0.1511
[332]	training's l2: 0.149248	valid_1's l2: 0.151023
[333]	training's l2: 0.149224	valid_1's l2: 0.15099

[471]	training's l2: 0.145522	valid_1's l2: 0.14784
[472]	training's l2: 0.145514	valid_1's l2: 0.147834
[473]	training's l2: 0.145508	valid_1's l2: 0.147828
[474]	training's l2: 0.1455	valid_1's l2: 0.147822
[475]	training's l2: 0.145492	valid_1's l2: 0.147814
[476]	training's l2: 0.145473	valid_1's l2: 0.147796
[477]	training's l2: 0.145418	valid_1's l2: 0.147753
[478]	training's l2: 0.145406	valid_1's l2: 0.147749
[479]	training's l2: 0.145378	valid_1's l2: 0.147727
[480]	training's l2: 0.145365	valid_1's l2: 0.147713
[481]	training's l2: 0.145338	valid_1's l2: 0.147696
[482]	training's l2: 0.14532	valid_1's l2: 0.147678
[483]	training's l2: 0.14531	valid_1's l2: 0.147668
[484]	training's l2: 0.145299	valid_1's l2: 0.14766
[485]	training's l2: 0.145288	valid_1's l2: 0.147651
[486]	training's l2: 0.145277	valid_1's l2: 0.14764
[487]	training's l2: 0.145258	valid_1's l2: 0.147624
[488]	training's l2: 0.145236	valid_1's l2: 0.147605
[489]	training's l2: 0.145217	valid_1's l2: 0.147587


[627]	training's l2: 0.14253	valid_1's l2: 0.145235
[628]	training's l2: 0.142515	valid_1's l2: 0.14522
[629]	training's l2: 0.142508	valid_1's l2: 0.145213
[630]	training's l2: 0.142492	valid_1's l2: 0.145201
[631]	training's l2: 0.142465	valid_1's l2: 0.145198
[632]	training's l2: 0.142453	valid_1's l2: 0.145189
[633]	training's l2: 0.142437	valid_1's l2: 0.145185
[634]	training's l2: 0.142431	valid_1's l2: 0.145181
[635]	training's l2: 0.142418	valid_1's l2: 0.145177
[636]	training's l2: 0.142406	valid_1's l2: 0.145166
[637]	training's l2: 0.142389	valid_1's l2: 0.145151
[638]	training's l2: 0.142384	valid_1's l2: 0.145146
[639]	training's l2: 0.142378	valid_1's l2: 0.145142
[640]	training's l2: 0.142368	valid_1's l2: 0.145129
[641]	training's l2: 0.142354	valid_1's l2: 0.145118
[642]	training's l2: 0.142341	valid_1's l2: 0.145112
[643]	training's l2: 0.142337	valid_1's l2: 0.145109
[644]	training's l2: 0.142324	valid_1's l2: 0.145097
[645]	training's l2: 0.142317	valid_1's l2: 0.14

[785]	training's l2: 0.140246	valid_1's l2: 0.143566
[786]	training's l2: 0.140238	valid_1's l2: 0.143558
[787]	training's l2: 0.140227	valid_1's l2: 0.143553
[788]	training's l2: 0.140218	valid_1's l2: 0.143545
[789]	training's l2: 0.140198	valid_1's l2: 0.143527
[790]	training's l2: 0.140171	valid_1's l2: 0.143502
[791]	training's l2: 0.140167	valid_1's l2: 0.143499
[792]	training's l2: 0.140158	valid_1's l2: 0.143491
[793]	training's l2: 0.14014	valid_1's l2: 0.143483
[794]	training's l2: 0.140129	valid_1's l2: 0.143474
[795]	training's l2: 0.140124	valid_1's l2: 0.14347
[796]	training's l2: 0.140113	valid_1's l2: 0.143458
[797]	training's l2: 0.140103	valid_1's l2: 0.14345
[798]	training's l2: 0.140098	valid_1's l2: 0.143447
[799]	training's l2: 0.140083	valid_1's l2: 0.143434
[800]	training's l2: 0.140069	valid_1's l2: 0.143421
[801]	training's l2: 0.140062	valid_1's l2: 0.143422
[802]	training's l2: 0.140056	valid_1's l2: 0.143417
[803]	training's l2: 0.140041	valid_1's l2: 0.143

[941]	training's l2: 0.138343	valid_1's l2: 0.142284
[942]	training's l2: 0.13833	valid_1's l2: 0.142278
[943]	training's l2: 0.13832	valid_1's l2: 0.142269
[944]	training's l2: 0.138307	valid_1's l2: 0.142259
[945]	training's l2: 0.138295	valid_1's l2: 0.14225
[946]	training's l2: 0.138292	valid_1's l2: 0.142247
[947]	training's l2: 0.138286	valid_1's l2: 0.142243
[948]	training's l2: 0.13826	valid_1's l2: 0.14224
[949]	training's l2: 0.138249	valid_1's l2: 0.142231
[950]	training's l2: 0.138237	valid_1's l2: 0.142228
[951]	training's l2: 0.138222	valid_1's l2: 0.142214
[952]	training's l2: 0.138198	valid_1's l2: 0.142186
[953]	training's l2: 0.138185	valid_1's l2: 0.142179
[954]	training's l2: 0.138172	valid_1's l2: 0.142167
[955]	training's l2: 0.138157	valid_1's l2: 0.142157
[956]	training's l2: 0.138147	valid_1's l2: 0.142148
[957]	training's l2: 0.138142	valid_1's l2: 0.142146
[958]	training's l2: 0.138132	valid_1's l2: 0.142144
[959]	training's l2: 0.138125	valid_1's l2: 0.14214

[1098]	training's l2: 0.136743	valid_1's l2: 0.141175
[1099]	training's l2: 0.136739	valid_1's l2: 0.141173
[1100]	training's l2: 0.136735	valid_1's l2: 0.14117
[1101]	training's l2: 0.136729	valid_1's l2: 0.141165
[1102]	training's l2: 0.136725	valid_1's l2: 0.14116
[1103]	training's l2: 0.136722	valid_1's l2: 0.141157
[1104]	training's l2: 0.136713	valid_1's l2: 0.141156
[1105]	training's l2: 0.136707	valid_1's l2: 0.14116
[1106]	training's l2: 0.136701	valid_1's l2: 0.141158
[1107]	training's l2: 0.136689	valid_1's l2: 0.141147
[1108]	training's l2: 0.136677	valid_1's l2: 0.141141
[1109]	training's l2: 0.136665	valid_1's l2: 0.141133
[1110]	training's l2: 0.136657	valid_1's l2: 0.141125
[1111]	training's l2: 0.136645	valid_1's l2: 0.141126
[1112]	training's l2: 0.136637	valid_1's l2: 0.141125
[1113]	training's l2: 0.136586	valid_1's l2: 0.141077
[1114]	training's l2: 0.13657	valid_1's l2: 0.14108
[1115]	training's l2: 0.136561	valid_1's l2: 0.141072
[1116]	training's l2: 0.13655	val

[1255]	training's l2: 0.135338	valid_1's l2: 0.140245
[1256]	training's l2: 0.135329	valid_1's l2: 0.140242
[1257]	training's l2: 0.135326	valid_1's l2: 0.140239
[1258]	training's l2: 0.135323	valid_1's l2: 0.140236
[1259]	training's l2: 0.135316	valid_1's l2: 0.140233
[1260]	training's l2: 0.135306	valid_1's l2: 0.140223
[1261]	training's l2: 0.135295	valid_1's l2: 0.140214
[1262]	training's l2: 0.135287	valid_1's l2: 0.140206
[1263]	training's l2: 0.135278	valid_1's l2: 0.140198
[1264]	training's l2: 0.135272	valid_1's l2: 0.140193
[1265]	training's l2: 0.135255	valid_1's l2: 0.140176
[1266]	training's l2: 0.135245	valid_1's l2: 0.140167
[1267]	training's l2: 0.135233	valid_1's l2: 0.140158
[1268]	training's l2: 0.135219	valid_1's l2: 0.140143
[1269]	training's l2: 0.135215	valid_1's l2: 0.14014
[1270]	training's l2: 0.135208	valid_1's l2: 0.140138
[1271]	training's l2: 0.135197	valid_1's l2: 0.14013
[1272]	training's l2: 0.135186	valid_1's l2: 0.140116
[1273]	training's l2: 0.135183

[1408]	training's l2: 0.134155	valid_1's l2: 0.139409
[1409]	training's l2: 0.134148	valid_1's l2: 0.139405
[1410]	training's l2: 0.134145	valid_1's l2: 0.139403
[1411]	training's l2: 0.134134	valid_1's l2: 0.139401
[1412]	training's l2: 0.134127	valid_1's l2: 0.139399
[1413]	training's l2: 0.13412	valid_1's l2: 0.1394
[1414]	training's l2: 0.134111	valid_1's l2: 0.139395
[1415]	training's l2: 0.134104	valid_1's l2: 0.139389
[1416]	training's l2: 0.134095	valid_1's l2: 0.139388
[1417]	training's l2: 0.134085	valid_1's l2: 0.139391
[1418]	training's l2: 0.134078	valid_1's l2: 0.139385
[1419]	training's l2: 0.134073	valid_1's l2: 0.139383
[1420]	training's l2: 0.134057	valid_1's l2: 0.139368
[1421]	training's l2: 0.134052	valid_1's l2: 0.139364
[1422]	training's l2: 0.134044	valid_1's l2: 0.139362
[1423]	training's l2: 0.134041	valid_1's l2: 0.13936
[1424]	training's l2: 0.134035	valid_1's l2: 0.139356
[1425]	training's l2: 0.134032	valid_1's l2: 0.139354
[1426]	training's l2: 0.134024	v

[1563]	training's l2: 0.132936	valid_1's l2: 0.13855
[1564]	training's l2: 0.13293	valid_1's l2: 0.138546
[1565]	training's l2: 0.132922	valid_1's l2: 0.138541
[1566]	training's l2: 0.132917	valid_1's l2: 0.138537
[1567]	training's l2: 0.132909	valid_1's l2: 0.138532
[1568]	training's l2: 0.132901	valid_1's l2: 0.13853
[1569]	training's l2: 0.132895	valid_1's l2: 0.138527
[1570]	training's l2: 0.132892	valid_1's l2: 0.138525
[1571]	training's l2: 0.13289	valid_1's l2: 0.138523
[1572]	training's l2: 0.132883	valid_1's l2: 0.138514
[1573]	training's l2: 0.132876	valid_1's l2: 0.13851
[1574]	training's l2: 0.132866	valid_1's l2: 0.138509
[1575]	training's l2: 0.132858	valid_1's l2: 0.138507
[1576]	training's l2: 0.132849	valid_1's l2: 0.138501
[1577]	training's l2: 0.132841	valid_1's l2: 0.138495
[1578]	training's l2: 0.13283	valid_1's l2: 0.138496
[1579]	training's l2: 0.132825	valid_1's l2: 0.138492
[1580]	training's l2: 0.132816	valid_1's l2: 0.138495
[1581]	training's l2: 0.132812	val

[1716]	training's l2: 0.131796	valid_1's l2: 0.137786
[1717]	training's l2: 0.131791	valid_1's l2: 0.137782
[1718]	training's l2: 0.131785	valid_1's l2: 0.137779
[1719]	training's l2: 0.131782	valid_1's l2: 0.137776
[1720]	training's l2: 0.13178	valid_1's l2: 0.137774
[1721]	training's l2: 0.131772	valid_1's l2: 0.137768
[1722]	training's l2: 0.13177	valid_1's l2: 0.137766
[1723]	training's l2: 0.131766	valid_1's l2: 0.137763
[1724]	training's l2: 0.13176	valid_1's l2: 0.137759
[1725]	training's l2: 0.131753	valid_1's l2: 0.137756
[1726]	training's l2: 0.131745	valid_1's l2: 0.13775
[1727]	training's l2: 0.131734	valid_1's l2: 0.137743
[1728]	training's l2: 0.131727	valid_1's l2: 0.13774
[1729]	training's l2: 0.131718	valid_1's l2: 0.137733
[1730]	training's l2: 0.131713	valid_1's l2: 0.13773
[1731]	training's l2: 0.13171	valid_1's l2: 0.137728
[1732]	training's l2: 0.131705	valid_1's l2: 0.137726
[1733]	training's l2: 0.131703	valid_1's l2: 0.137724
[1734]	training's l2: 0.131696	vali

[1870]	training's l2: 0.130779	valid_1's l2: 0.137028
[1871]	training's l2: 0.130767	valid_1's l2: 0.137017
[1872]	training's l2: 0.130761	valid_1's l2: 0.137011
[1873]	training's l2: 0.130758	valid_1's l2: 0.13701
[1874]	training's l2: 0.130752	valid_1's l2: 0.137008
[1875]	training's l2: 0.130749	valid_1's l2: 0.137005
[1876]	training's l2: 0.130744	valid_1's l2: 0.137002
[1877]	training's l2: 0.130739	valid_1's l2: 0.136997
[1878]	training's l2: 0.13073	valid_1's l2: 0.13699
[1879]	training's l2: 0.130725	valid_1's l2: 0.136986
[1880]	training's l2: 0.130717	valid_1's l2: 0.136978
[1881]	training's l2: 0.13071	valid_1's l2: 0.136972
[1882]	training's l2: 0.130702	valid_1's l2: 0.136968
[1883]	training's l2: 0.130696	valid_1's l2: 0.136962
[1884]	training's l2: 0.130688	valid_1's l2: 0.136955
[1885]	training's l2: 0.13068	valid_1's l2: 0.136949
[1886]	training's l2: 0.130672	valid_1's l2: 0.136948
[1887]	training's l2: 0.130664	valid_1's l2: 0.136941
[1888]	training's l2: 0.130657	va

[2027]	training's l2: 0.129695	valid_1's l2: 0.136288
[2028]	training's l2: 0.129687	valid_1's l2: 0.136282
[2029]	training's l2: 0.129683	valid_1's l2: 0.136279
[2030]	training's l2: 0.129679	valid_1's l2: 0.136276
[2031]	training's l2: 0.129672	valid_1's l2: 0.136269
[2032]	training's l2: 0.129671	valid_1's l2: 0.136268
[2033]	training's l2: 0.129668	valid_1's l2: 0.136266
[2034]	training's l2: 0.129662	valid_1's l2: 0.136264
[2035]	training's l2: 0.129656	valid_1's l2: 0.136262
[2036]	training's l2: 0.129651	valid_1's l2: 0.136257
[2037]	training's l2: 0.129647	valid_1's l2: 0.136255
[2038]	training's l2: 0.129645	valid_1's l2: 0.136254
[2039]	training's l2: 0.129641	valid_1's l2: 0.136252
[2040]	training's l2: 0.129634	valid_1's l2: 0.13625
[2041]	training's l2: 0.129629	valid_1's l2: 0.136247
[2042]	training's l2: 0.129627	valid_1's l2: 0.136243
[2043]	training's l2: 0.129625	valid_1's l2: 0.136241
[2044]	training's l2: 0.129617	valid_1's l2: 0.136238
[2045]	training's l2: 0.12961

[2180]	training's l2: 0.12882	valid_1's l2: 0.135742
[2181]	training's l2: 0.128811	valid_1's l2: 0.135735
[2182]	training's l2: 0.128803	valid_1's l2: 0.135727
[2183]	training's l2: 0.128796	valid_1's l2: 0.135722
[2184]	training's l2: 0.128789	valid_1's l2: 0.13572
[2185]	training's l2: 0.128785	valid_1's l2: 0.135716
[2186]	training's l2: 0.128758	valid_1's l2: 0.135682
[2187]	training's l2: 0.128754	valid_1's l2: 0.13568
[2188]	training's l2: 0.128753	valid_1's l2: 0.135681
[2189]	training's l2: 0.128748	valid_1's l2: 0.135678
[2190]	training's l2: 0.128742	valid_1's l2: 0.135676
[2191]	training's l2: 0.128709	valid_1's l2: 0.135652
[2192]	training's l2: 0.128706	valid_1's l2: 0.13565
[2193]	training's l2: 0.128703	valid_1's l2: 0.135648
[2194]	training's l2: 0.1287	valid_1's l2: 0.135647
[2195]	training's l2: 0.128698	valid_1's l2: 0.135645
[2196]	training's l2: 0.128694	valid_1's l2: 0.135642
[2197]	training's l2: 0.128691	valid_1's l2: 0.13564
[2198]	training's l2: 0.128685	vali

[2334]	training's l2: 0.127966	valid_1's l2: 0.13515
[2335]	training's l2: 0.127962	valid_1's l2: 0.135144
[2336]	training's l2: 0.127955	valid_1's l2: 0.135139
[2337]	training's l2: 0.127949	valid_1's l2: 0.135135
[2338]	training's l2: 0.127947	valid_1's l2: 0.135134
[2339]	training's l2: 0.127944	valid_1's l2: 0.135132
[2340]	training's l2: 0.12794	valid_1's l2: 0.135128
[2341]	training's l2: 0.127935	valid_1's l2: 0.135127
[2342]	training's l2: 0.127928	valid_1's l2: 0.135122
[2343]	training's l2: 0.127926	valid_1's l2: 0.135122
[2344]	training's l2: 0.127921	valid_1's l2: 0.135118
[2345]	training's l2: 0.127917	valid_1's l2: 0.135115
[2346]	training's l2: 0.127915	valid_1's l2: 0.135114
[2347]	training's l2: 0.127908	valid_1's l2: 0.135109
[2348]	training's l2: 0.127906	valid_1's l2: 0.135108
[2349]	training's l2: 0.127904	valid_1's l2: 0.135105
[2350]	training's l2: 0.127899	valid_1's l2: 0.135101
[2351]	training's l2: 0.127897	valid_1's l2: 0.135099
[2352]	training's l2: 0.12789	

[2491]	training's l2: 0.12718	valid_1's l2: 0.134628
[2492]	training's l2: 0.127171	valid_1's l2: 0.134618
[2493]	training's l2: 0.127169	valid_1's l2: 0.134617
[2494]	training's l2: 0.127164	valid_1's l2: 0.134616
[2495]	training's l2: 0.127159	valid_1's l2: 0.134614
[2496]	training's l2: 0.127157	valid_1's l2: 0.134612
[2497]	training's l2: 0.127154	valid_1's l2: 0.13461
[2498]	training's l2: 0.127146	valid_1's l2: 0.134604
[2499]	training's l2: 0.127142	valid_1's l2: 0.134601
[2500]	training's l2: 0.127127	valid_1's l2: 0.134597
[2501]	training's l2: 0.127123	valid_1's l2: 0.134593
[2502]	training's l2: 0.127116	valid_1's l2: 0.134589
[2503]	training's l2: 0.127111	valid_1's l2: 0.13459
[2504]	training's l2: 0.127106	valid_1's l2: 0.134587
[2505]	training's l2: 0.1271	valid_1's l2: 0.134584
[2506]	training's l2: 0.127096	valid_1's l2: 0.134581
[2507]	training's l2: 0.127091	valid_1's l2: 0.134579
[2508]	training's l2: 0.127084	valid_1's l2: 0.134576
[2509]	training's l2: 0.127075	va

[2644]	training's l2: 0.126496	valid_1's l2: 0.134208
[2645]	training's l2: 0.126489	valid_1's l2: 0.134207
[2646]	training's l2: 0.126485	valid_1's l2: 0.134204
[2647]	training's l2: 0.126478	valid_1's l2: 0.134201
[2648]	training's l2: 0.126473	valid_1's l2: 0.134198
[2649]	training's l2: 0.126464	valid_1's l2: 0.134186
[2650]	training's l2: 0.126459	valid_1's l2: 0.134184
[2651]	training's l2: 0.126456	valid_1's l2: 0.134182
[2652]	training's l2: 0.126449	valid_1's l2: 0.134174
[2653]	training's l2: 0.126445	valid_1's l2: 0.13417
[2654]	training's l2: 0.12644	valid_1's l2: 0.134169
[2655]	training's l2: 0.126435	valid_1's l2: 0.134165
[2656]	training's l2: 0.126431	valid_1's l2: 0.134162
[2657]	training's l2: 0.126425	valid_1's l2: 0.134158
[2658]	training's l2: 0.126419	valid_1's l2: 0.134155
[2659]	training's l2: 0.126414	valid_1's l2: 0.13415
[2660]	training's l2: 0.12641	valid_1's l2: 0.134148
[2661]	training's l2: 0.126404	valid_1's l2: 0.134149
[2662]	training's l2: 0.1264	val

[2801]	training's l2: 0.125821	valid_1's l2: 0.133804
[2802]	training's l2: 0.125817	valid_1's l2: 0.133802
[2803]	training's l2: 0.125813	valid_1's l2: 0.133797
[2804]	training's l2: 0.125809	valid_1's l2: 0.133794
[2805]	training's l2: 0.125806	valid_1's l2: 0.133793
[2806]	training's l2: 0.125799	valid_1's l2: 0.133793
[2807]	training's l2: 0.125772	valid_1's l2: 0.133771
[2808]	training's l2: 0.125767	valid_1's l2: 0.133768
[2809]	training's l2: 0.125762	valid_1's l2: 0.133763
[2810]	training's l2: 0.125756	valid_1's l2: 0.13376
[2811]	training's l2: 0.125754	valid_1's l2: 0.133758
[2812]	training's l2: 0.125752	valid_1's l2: 0.133759
[2813]	training's l2: 0.125749	valid_1's l2: 0.133757
[2814]	training's l2: 0.125744	valid_1's l2: 0.133754
[2815]	training's l2: 0.125739	valid_1's l2: 0.133749
[2816]	training's l2: 0.125735	valid_1's l2: 0.133746
[2817]	training's l2: 0.125733	valid_1's l2: 0.133745
[2818]	training's l2: 0.125724	valid_1's l2: 0.133739
[2819]	training's l2: 0.12572

[2957]	training's l2: 0.125138	valid_1's l2: 0.133366
[2958]	training's l2: 0.125137	valid_1's l2: 0.133365
[2959]	training's l2: 0.125132	valid_1's l2: 0.133365
[2960]	training's l2: 0.125126	valid_1's l2: 0.13336
[2961]	training's l2: 0.125125	valid_1's l2: 0.133359
[2962]	training's l2: 0.125122	valid_1's l2: 0.133357
[2963]	training's l2: 0.125116	valid_1's l2: 0.133353
[2964]	training's l2: 0.125115	valid_1's l2: 0.133352
[2965]	training's l2: 0.125113	valid_1's l2: 0.133351
[2966]	training's l2: 0.125111	valid_1's l2: 0.13335
[2967]	training's l2: 0.125107	valid_1's l2: 0.133348
[2968]	training's l2: 0.125103	valid_1's l2: 0.133344
[2969]	training's l2: 0.125099	valid_1's l2: 0.133343
[2970]	training's l2: 0.125096	valid_1's l2: 0.133342
[2971]	training's l2: 0.125092	valid_1's l2: 0.133339
[2972]	training's l2: 0.125091	valid_1's l2: 0.133337
[2973]	training's l2: 0.125087	valid_1's l2: 0.133336
[2974]	training's l2: 0.125082	valid_1's l2: 0.133337
[2975]	training's l2: 0.125076

[3110]	training's l2: 0.124555	valid_1's l2: 0.133033
[3111]	training's l2: 0.124553	valid_1's l2: 0.133031
[3112]	training's l2: 0.124548	valid_1's l2: 0.133029
[3113]	training's l2: 0.124546	valid_1's l2: 0.133027
[3114]	training's l2: 0.124544	valid_1's l2: 0.133025
[3115]	training's l2: 0.12454	valid_1's l2: 0.133023
[3116]	training's l2: 0.124537	valid_1's l2: 0.13302
[3117]	training's l2: 0.12453	valid_1's l2: 0.133014
[3118]	training's l2: 0.124529	valid_1's l2: 0.133013
[3119]	training's l2: 0.124524	valid_1's l2: 0.133012
[3120]	training's l2: 0.124522	valid_1's l2: 0.13301
[3121]	training's l2: 0.124519	valid_1's l2: 0.133008
[3122]	training's l2: 0.124515	valid_1's l2: 0.133004
[3123]	training's l2: 0.124512	valid_1's l2: 0.133002
[3124]	training's l2: 0.124509	valid_1's l2: 0.132999
[3125]	training's l2: 0.124502	valid_1's l2: 0.132994
[3126]	training's l2: 0.124497	valid_1's l2: 0.132991
[3127]	training's l2: 0.124492	valid_1's l2: 0.132986
[3128]	training's l2: 0.124489	v

[3265]	training's l2: 0.123956	valid_1's l2: 0.13265
[3266]	training's l2: 0.123955	valid_1's l2: 0.13265
[3267]	training's l2: 0.123951	valid_1's l2: 0.132645
[3268]	training's l2: 0.123948	valid_1's l2: 0.132643
[3269]	training's l2: 0.123944	valid_1's l2: 0.13264
[3270]	training's l2: 0.123938	valid_1's l2: 0.132636
[3271]	training's l2: 0.123933	valid_1's l2: 0.132632
[3272]	training's l2: 0.12393	valid_1's l2: 0.132629
[3273]	training's l2: 0.123926	valid_1's l2: 0.132627
[3274]	training's l2: 0.123923	valid_1's l2: 0.132625
[3275]	training's l2: 0.123921	valid_1's l2: 0.132624
[3276]	training's l2: 0.123919	valid_1's l2: 0.132623
[3277]	training's l2: 0.123913	valid_1's l2: 0.132616
[3278]	training's l2: 0.123902	valid_1's l2: 0.132619
[3279]	training's l2: 0.123898	valid_1's l2: 0.132615
[3280]	training's l2: 0.123896	valid_1's l2: 0.132613
[3281]	training's l2: 0.123885	valid_1's l2: 0.13261
[3282]	training's l2: 0.123881	valid_1's l2: 0.132609
[3283]	training's l2: 0.123876	va

[3420]	training's l2: 0.123363	valid_1's l2: 0.132285
[3421]	training's l2: 0.123361	valid_1's l2: 0.132285
[3422]	training's l2: 0.123358	valid_1's l2: 0.132281
[3423]	training's l2: 0.123355	valid_1's l2: 0.132279
[3424]	training's l2: 0.123349	valid_1's l2: 0.132274
[3425]	training's l2: 0.123345	valid_1's l2: 0.13227
[3426]	training's l2: 0.123341	valid_1's l2: 0.132268
[3427]	training's l2: 0.123339	valid_1's l2: 0.132266
[3428]	training's l2: 0.123335	valid_1's l2: 0.132263
[3429]	training's l2: 0.123333	valid_1's l2: 0.132263
[3430]	training's l2: 0.123329	valid_1's l2: 0.132263
[3431]	training's l2: 0.123325	valid_1's l2: 0.132261
[3432]	training's l2: 0.123319	valid_1's l2: 0.132258
[3433]	training's l2: 0.123316	valid_1's l2: 0.132255
[3434]	training's l2: 0.123311	valid_1's l2: 0.132251
[3435]	training's l2: 0.123307	valid_1's l2: 0.132249
[3436]	training's l2: 0.123303	valid_1's l2: 0.132245
[3437]	training's l2: 0.1233	valid_1's l2: 0.132243
[3438]	training's l2: 0.123297	

[3576]	training's l2: 0.122824	valid_1's l2: 0.131974
[3577]	training's l2: 0.12282	valid_1's l2: 0.131971
[3578]	training's l2: 0.122818	valid_1's l2: 0.131969
[3579]	training's l2: 0.122813	valid_1's l2: 0.131969
[3580]	training's l2: 0.122809	valid_1's l2: 0.131969
[3581]	training's l2: 0.122808	valid_1's l2: 0.131967
[3582]	training's l2: 0.122804	valid_1's l2: 0.131964
[3583]	training's l2: 0.122802	valid_1's l2: 0.131962
[3584]	training's l2: 0.122798	valid_1's l2: 0.131959
[3585]	training's l2: 0.122795	valid_1's l2: 0.131958
[3586]	training's l2: 0.122793	valid_1's l2: 0.131957
[3587]	training's l2: 0.122791	valid_1's l2: 0.131955
[3588]	training's l2: 0.122784	valid_1's l2: 0.131948
[3589]	training's l2: 0.12278	valid_1's l2: 0.131946
[3590]	training's l2: 0.122778	valid_1's l2: 0.131945
[3591]	training's l2: 0.122771	valid_1's l2: 0.131939
[3592]	training's l2: 0.122771	valid_1's l2: 0.131938
[3593]	training's l2: 0.122768	valid_1's l2: 0.131935
[3594]	training's l2: 0.122763

[3732]	training's l2: 0.122299	valid_1's l2: 0.131654
[3733]	training's l2: 0.122294	valid_1's l2: 0.131651
[3734]	training's l2: 0.122291	valid_1's l2: 0.13165
[3735]	training's l2: 0.122288	valid_1's l2: 0.131648
[3736]	training's l2: 0.122285	valid_1's l2: 0.131645
[3737]	training's l2: 0.122283	valid_1's l2: 0.131644
[3738]	training's l2: 0.12228	valid_1's l2: 0.131641
[3739]	training's l2: 0.122277	valid_1's l2: 0.131639
[3740]	training's l2: 0.122272	valid_1's l2: 0.131636
[3741]	training's l2: 0.122269	valid_1's l2: 0.131634
[3742]	training's l2: 0.122267	valid_1's l2: 0.131633
[3743]	training's l2: 0.122264	valid_1's l2: 0.13163
[3744]	training's l2: 0.122262	valid_1's l2: 0.131629
[3745]	training's l2: 0.122261	valid_1's l2: 0.131629
[3746]	training's l2: 0.122258	valid_1's l2: 0.131626
[3747]	training's l2: 0.122258	valid_1's l2: 0.131625
[3748]	training's l2: 0.122251	valid_1's l2: 0.131619
[3749]	training's l2: 0.122247	valid_1's l2: 0.131618
[3750]	training's l2: 0.122243	

[3886]	training's l2: 0.121794	valid_1's l2: 0.131346
[3887]	training's l2: 0.12179	valid_1's l2: 0.131343
[3888]	training's l2: 0.121788	valid_1's l2: 0.131342
[3889]	training's l2: 0.121785	valid_1's l2: 0.131339
[3890]	training's l2: 0.121781	valid_1's l2: 0.131336
[3891]	training's l2: 0.121779	valid_1's l2: 0.131335
[3892]	training's l2: 0.121777	valid_1's l2: 0.131333
[3893]	training's l2: 0.121774	valid_1's l2: 0.131329
[3894]	training's l2: 0.121771	valid_1's l2: 0.131328
[3895]	training's l2: 0.121767	valid_1's l2: 0.131326
[3896]	training's l2: 0.121765	valid_1's l2: 0.131324
[3897]	training's l2: 0.121762	valid_1's l2: 0.131321
[3898]	training's l2: 0.121761	valid_1's l2: 0.13132
[3899]	training's l2: 0.121759	valid_1's l2: 0.131319
[3900]	training's l2: 0.121758	valid_1's l2: 0.131318
[3901]	training's l2: 0.121754	valid_1's l2: 0.131316
[3902]	training's l2: 0.12175	valid_1's l2: 0.131317
[3903]	training's l2: 0.121747	valid_1's l2: 0.131314
[3904]	training's l2: 0.121743	

[4040]	training's l2: 0.121304	valid_1's l2: 0.131044
[4041]	training's l2: 0.1213	valid_1's l2: 0.131042
[4042]	training's l2: 0.121296	valid_1's l2: 0.131039
[4043]	training's l2: 0.121292	valid_1's l2: 0.131037
[4044]	training's l2: 0.121288	valid_1's l2: 0.131036
[4045]	training's l2: 0.121286	valid_1's l2: 0.131035
[4046]	training's l2: 0.121278	valid_1's l2: 0.131028
[4047]	training's l2: 0.121274	valid_1's l2: 0.131029
[4048]	training's l2: 0.121272	valid_1's l2: 0.131028
[4049]	training's l2: 0.12127	valid_1's l2: 0.131027
[4050]	training's l2: 0.121265	valid_1's l2: 0.131027
[4051]	training's l2: 0.121261	valid_1's l2: 0.131025
[4052]	training's l2: 0.121257	valid_1's l2: 0.131022
[4053]	training's l2: 0.121246	valid_1's l2: 0.131014
[4054]	training's l2: 0.121244	valid_1's l2: 0.131015
[4055]	training's l2: 0.121243	valid_1's l2: 0.131015
[4056]	training's l2: 0.121239	valid_1's l2: 0.131013
[4057]	training's l2: 0.121238	valid_1's l2: 0.131014
[4058]	training's l2: 0.121235	

[4196]	training's l2: 0.120793	valid_1's l2: 0.130763
[4197]	training's l2: 0.120789	valid_1's l2: 0.130761
[4198]	training's l2: 0.120785	valid_1's l2: 0.130759
[4199]	training's l2: 0.120782	valid_1's l2: 0.130757
[4200]	training's l2: 0.120777	valid_1's l2: 0.130751
[4201]	training's l2: 0.120774	valid_1's l2: 0.130748
[4202]	training's l2: 0.120768	valid_1's l2: 0.130744
[4203]	training's l2: 0.120763	valid_1's l2: 0.130746
[4204]	training's l2: 0.120756	valid_1's l2: 0.13075
[4205]	training's l2: 0.120752	valid_1's l2: 0.130749
[4206]	training's l2: 0.120748	valid_1's l2: 0.130749
[4207]	training's l2: 0.120745	valid_1's l2: 0.130747
[4208]	training's l2: 0.120743	valid_1's l2: 0.130745
[4209]	training's l2: 0.12074	valid_1's l2: 0.130743
[4210]	training's l2: 0.120737	valid_1's l2: 0.130743
[4211]	training's l2: 0.120734	valid_1's l2: 0.130741
[4212]	training's l2: 0.120732	valid_1's l2: 0.13074
[4213]	training's l2: 0.120729	valid_1's l2: 0.130738
[4214]	training's l2: 0.120725	

[4352]	training's l2: 0.12032	valid_1's l2: 0.130485
[4353]	training's l2: 0.120316	valid_1's l2: 0.130483
[4354]	training's l2: 0.120313	valid_1's l2: 0.13048
[4355]	training's l2: 0.120312	valid_1's l2: 0.130482
[4356]	training's l2: 0.120309	valid_1's l2: 0.130481
[4357]	training's l2: 0.120307	valid_1's l2: 0.130482
[4358]	training's l2: 0.120305	valid_1's l2: 0.130481
[4359]	training's l2: 0.120302	valid_1's l2: 0.13048
[4360]	training's l2: 0.120299	valid_1's l2: 0.130477
[4361]	training's l2: 0.120296	valid_1's l2: 0.130476
[4362]	training's l2: 0.120294	valid_1's l2: 0.130474
[4363]	training's l2: 0.120293	valid_1's l2: 0.130474
[4364]	training's l2: 0.120292	valid_1's l2: 0.130473
[4365]	training's l2: 0.12029	valid_1's l2: 0.130472
[4366]	training's l2: 0.120283	valid_1's l2: 0.130465
[4367]	training's l2: 0.12028	valid_1's l2: 0.130462
[4368]	training's l2: 0.120277	valid_1's l2: 0.13046
[4369]	training's l2: 0.120274	valid_1's l2: 0.130459
[4370]	training's l2: 0.12027	vali

[4506]	training's l2: 0.119888	valid_1's l2: 0.13021
[4507]	training's l2: 0.119885	valid_1's l2: 0.130209
[4508]	training's l2: 0.119882	valid_1's l2: 0.130207
[4509]	training's l2: 0.119879	valid_1's l2: 0.130206
[4510]	training's l2: 0.119877	valid_1's l2: 0.130206
[4511]	training's l2: 0.119875	valid_1's l2: 0.130205
[4512]	training's l2: 0.119873	valid_1's l2: 0.130204
[4513]	training's l2: 0.11987	valid_1's l2: 0.130202
[4514]	training's l2: 0.119867	valid_1's l2: 0.130201
[4515]	training's l2: 0.119864	valid_1's l2: 0.1302
[4516]	training's l2: 0.119861	valid_1's l2: 0.130199
[4517]	training's l2: 0.119859	valid_1's l2: 0.130198
[4518]	training's l2: 0.119857	valid_1's l2: 0.130197
[4519]	training's l2: 0.119854	valid_1's l2: 0.130195
[4520]	training's l2: 0.119852	valid_1's l2: 0.130194
[4521]	training's l2: 0.119849	valid_1's l2: 0.13019
[4522]	training's l2: 0.119847	valid_1's l2: 0.130188
[4523]	training's l2: 0.119836	valid_1's l2: 0.130173
[4524]	training's l2: 0.119833	va

[4662]	training's l2: 0.119428	valid_1's l2: 0.129951
[4663]	training's l2: 0.119426	valid_1's l2: 0.12995
[4664]	training's l2: 0.119421	valid_1's l2: 0.129944
[4665]	training's l2: 0.119418	valid_1's l2: 0.129942
[4666]	training's l2: 0.119413	valid_1's l2: 0.129937
[4667]	training's l2: 0.119409	valid_1's l2: 0.129936
[4668]	training's l2: 0.119404	valid_1's l2: 0.129933
[4669]	training's l2: 0.119399	valid_1's l2: 0.129929
[4670]	training's l2: 0.11939	valid_1's l2: 0.129917
[4671]	training's l2: 0.119387	valid_1's l2: 0.129916
[4672]	training's l2: 0.119383	valid_1's l2: 0.129915
[4673]	training's l2: 0.11938	valid_1's l2: 0.129911
[4674]	training's l2: 0.119377	valid_1's l2: 0.12991
[4675]	training's l2: 0.119373	valid_1's l2: 0.129911
[4676]	training's l2: 0.11937	valid_1's l2: 0.12991
[4677]	training's l2: 0.119367	valid_1's l2: 0.129907
[4678]	training's l2: 0.119364	valid_1's l2: 0.129906
[4679]	training's l2: 0.119361	valid_1's l2: 0.129905
[4680]	training's l2: 0.11936	vali

[4818]	training's l2: 0.118987	valid_1's l2: 0.12969
[4819]	training's l2: 0.118985	valid_1's l2: 0.12969
[4820]	training's l2: 0.118983	valid_1's l2: 0.129689
[4821]	training's l2: 0.118981	valid_1's l2: 0.129692
[4822]	training's l2: 0.118979	valid_1's l2: 0.129691
[4823]	training's l2: 0.118977	valid_1's l2: 0.12969
[4824]	training's l2: 0.118975	valid_1's l2: 0.12969
[4825]	training's l2: 0.118971	valid_1's l2: 0.129687
[4826]	training's l2: 0.118968	valid_1's l2: 0.129684
[4827]	training's l2: 0.118964	valid_1's l2: 0.129681
[4828]	training's l2: 0.11896	valid_1's l2: 0.129682
[4829]	training's l2: 0.118958	valid_1's l2: 0.129683
[4830]	training's l2: 0.118956	valid_1's l2: 0.12968
[4831]	training's l2: 0.118953	valid_1's l2: 0.129678
[4832]	training's l2: 0.11895	valid_1's l2: 0.129676
[4833]	training's l2: 0.118948	valid_1's l2: 0.129675
[4834]	training's l2: 0.118945	valid_1's l2: 0.129672
[4835]	training's l2: 0.118944	valid_1's l2: 0.129672
[4836]	training's l2: 0.118938	vali

[4972]	training's l2: 0.118563	valid_1's l2: 0.129439
[4973]	training's l2: 0.118562	valid_1's l2: 0.129439
[4974]	training's l2: 0.118557	valid_1's l2: 0.129437
[4975]	training's l2: 0.118555	valid_1's l2: 0.129436
[4976]	training's l2: 0.118553	valid_1's l2: 0.129434
[4977]	training's l2: 0.11855	valid_1's l2: 0.129432
[4978]	training's l2: 0.118548	valid_1's l2: 0.129431
[4979]	training's l2: 0.118546	valid_1's l2: 0.129429
[4980]	training's l2: 0.118543	valid_1's l2: 0.129426
[4981]	training's l2: 0.118541	valid_1's l2: 0.129425
[4982]	training's l2: 0.118539	valid_1's l2: 0.129423
[4983]	training's l2: 0.118533	valid_1's l2: 0.129423
[4984]	training's l2: 0.11853	valid_1's l2: 0.12942
[4985]	training's l2: 0.118526	valid_1's l2: 0.129417
[4986]	training's l2: 0.118524	valid_1's l2: 0.129416
[4987]	training's l2: 0.118522	valid_1's l2: 0.129416
[4988]	training's l2: 0.118518	valid_1's l2: 0.129413
[4989]	training's l2: 0.118516	valid_1's l2: 0.129412
[4990]	training's l2: 0.118513	

In [15]:
y_pred_train = lgb.predict(X_train, num_iteration=lgb.best_iteration)
y_pred_train[y_pred_train < 0] = 0
y_pred_val = lgb.predict(X_val, num_iteration=lgb.best_iteration)
y_pred_val[y_pred_val < 0] = 0

print("RMS log-error train: ", np.sqrt(mean_squared_log_error(y_train, y_pred_train)))
print("RMS log-error val: ", np.sqrt(mean_squared_log_error(y_val, y_pred_val)))

RMS log-error train:  0.1387609500374927
RMS log-error val:  0.14257049755882722


## Experiment III -- Random Forest (Too Slow)

In [16]:
# random_forest = RandomForestRegressor(random_state=1)
# random_forest.fit(X_train, y_train)

In [17]:
# y_pred_train = random_forest.predict(X_train)
# y_pred_train[y_pred_train < 0] = 0
# y_pred_val = random_forest.predict(X_val)
# y_pred_val[y_pred_val < 0] = 0
# 
# print("RMS log-error train: ", np.sqrt(mean_squared_log_error(y_train, y_pred_train)))
# print("RMS log-error val: ", np.sqrt(mean_squared_log_error(y_val, y_pred_val)))

## Experiment IV -- XGBoost

In [18]:
xgb = xgboost.XGBRegressor(n_estimators=100, early_stopping_rounds=50, learning_rate=0.3)
xgb.fit(X_train, y_train,
        eval_set=[(X_train, y_train), (X_val, y_val)],
        verbose=True)

[0]	validation_0-rmse:2.71987	validation_1-rmse:2.72299
[1]	validation_0-rmse:1.93035	validation_1-rmse:1.93278
[2]	validation_0-rmse:1.38620	validation_1-rmse:1.38824
[3]	validation_0-rmse:1.01648	validation_1-rmse:1.01831
[4]	validation_0-rmse:0.77172	validation_1-rmse:0.77343
[5]	validation_0-rmse:0.61584	validation_1-rmse:0.61747
[6]	validation_0-rmse:0.52174	validation_1-rmse:0.52354
[7]	validation_0-rmse:0.46771	validation_1-rmse:0.46957
[8]	validation_0-rmse:0.43778	validation_1-rmse:0.43960
[9]	validation_0-rmse:0.42168	validation_1-rmse:0.42367
[10]	validation_0-rmse:0.41267	validation_1-rmse:0.41490
[11]	validation_0-rmse:0.40735	validation_1-rmse:0.40977
[12]	validation_0-rmse:0.40454	validation_1-rmse:0.40705
[13]	validation_0-rmse:0.40260	validation_1-rmse:0.40516
[14]	validation_0-rmse:0.40071	validation_1-rmse:0.40338
[15]	validation_0-rmse:0.39936	validation_1-rmse:0.40220
[16]	validation_0-rmse:0.39789	validation_1-rmse:0.40095
[17]	validation_0-rmse:0.39717	validation

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=50, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.3, max_bin=256,
             max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
             max_depth=6, max_leaves=0, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [19]:
y_pred_train = xgb.predict(X_train)
y_pred_train[y_pred_train < 0] = 0
y_pred_val = xgb.predict(X_val)
y_pred_val[y_pred_val < 0] = 0

print("RMS log-error train: ", np.sqrt(mean_squared_log_error(y_train, y_pred_train)))
print("RMS log-error val: ", np.sqrt(mean_squared_log_error(y_val, y_pred_val)))

RMS log-error train:  0.14580213414791765
RMS log-error val:  0.148140172363345


## Test (Moment of Truth)

In [20]:
def main_predict(model, X_test):
    X_test_mod = X_test.copy()
    output = np.array([])
    start_day, end_day = X_test['day_of_month'].min(), X_test['day_of_month'].max()
        # we lost the dates, but we still have day_of_month, which is good enough for our experiment
        
    for day in range(start_day, end_day + 1):
        pred = model.predict(X_test_mod[X_test_mod['day_of_month'] == day])
        pred[pred < 0] = 0
        print(pred)
        output = np.concatenate([output, pred], axis=0)
        for future in range(day + 1, end_day + 1):
            X_test_mod.loc[X_test_mod[X_test_mod['day_of_month'] == future].index,
                           f'sales_lag_{(future - day):02d}'] = pred
            # fill out future values now that this sales figure is available
            
    return output

In [22]:
y_pred_test = main_predict(lgb, X_test)

[1.71110834 0.08379029 1.81252702 ... 7.39744987 4.69015147 2.72674146]
[1.66971891 0.16332013 1.62072741 ... 7.1026506  4.75359562 2.74782741]
[1.65037821 0.25248781 1.59161123 ... 7.21360495 4.56534682 2.71157835]
[1.69302112 0.26195894 1.64988892 ... 7.36286941 4.90834782 3.03219422]
[1.33943444 0.22488158 1.25700134 ... 7.50540871 5.28738142 3.10238349]
[1.80396964 0.45999522 1.7878795  ... 7.28954287 5.00519199 2.79132473]
[1.6229337  0.47176165 1.51336683 ... 7.75689353 4.862333   2.73353559]
[1.80236967 0.49506213 1.74457141 ... 7.25184884 4.55856768 2.65561607]
[1.58855556 0.45262751 1.55163497 ... 7.08625759 4.65245023 2.6803464 ]
[1.67862865 0.51737878 1.52286322 ... 7.19894014 4.47835593 2.69521436]
[1.72424265 0.49387913 1.68222807 ... 7.38367885 4.85324375 3.19632852]
[1.31565798 0.37330859 1.32004018 ... 7.4995543  5.25334404 3.12507901]
[1.71209913 0.614586   1.75465548 ... 7.16633549 5.03806483 2.67560275]
[1.63097807 0.63489693 1.6891822  ... 7.74792852 4.76284994 2.70

In [25]:
delta_index = 3008016 - 3000888  # we inserted 4 Christmas days, 4 x 54 x 33 = 7128, which is the difference
submission = pd.DataFrame({'id': X_test.index - delta_index, 'sales': np.expm1(y_pred_test)})
submission.to_csv('submission.csv', index=False)